### ISSUE TITLE
Complicated: clear button

### ISSUE THREAD

**Issue by CyanRibena** [halojenproductions/KtneSolver#30]
Unexpected behaviour:
Optional buttons do not reset on clear button click. This is actually a great feature as they persist while the bomb is defused, since there may be a need for this information across other modules. 

Im not sure how this logic _should_ work when the radio buttons are merged in. I think if there is no selection then these optional buttons should hide on clear, if there is a radio selection then persist.

**Comment by halojenproductions** [comment]
Yup, they could hide when not needed (i.e. when there are no buttons selected in the top section) but they should retain their value when reset is clicked (so they should be outside the form).
