### ISSUE TITLE
Missile Buttons

### ISSUE THREAD

**Issue by CyanRibena** [halojenproductions/KtneSolver#9]
Current test cases missing a result.

3. If the word is detonate (any colour) and zero cells, then should display the hold instructions.
4. If the colour is white (any word except detonate) and no CAR indicator, then should display hold instructions.

There could be 1 cell on the bomb which logically is the "no cells" button, if I have sunstroke again, I could get confused by the buttons label.

Personally, I'm not sure that there needs to be a hold variable and a click variable as they are not mutually exclusive, but this works so no need to change it.

**Comment by halojenproductions** [comment]
- Test cases added: `Any colour, detonate, No cells`; `White, abort or hold, no CAR`

- No cells button is renamed to "<=1".

I think you meant because they _are_ mutually exclusive. But remember there are 3 outcomes in total: Unknown; Hold; Click.

**Comment by halojenproductions** [comment]
@CyanRibena I'm not sure about "White, abort or hold, no CAR" (case 3 on the manual) because I think if it has no CAR then it should fall through to case 4 where it ask about batteries and FRK. What do you think?
